### ISSUE TITLE
Locale string 'es-ES_tradnl' not being handled

### ISSUE THREAD

**Issue by craiga** [craiga/unixtimesta.mp#110]
https://sentry.io/craig-anderson/unixtimestamp/issues/527681855/

```
RangeError: La configuración regional 'es-ES_tradnl' no tiene el formato correcto
  at Anonymous function (/1005821864:47:9)
  at j (/jquery-3.1.1.slim.min.js:2:30157)
  at Anonymous function (/jquery-3.1.1.slim.min.js:2:30478)
```

**Comment by craiga** [comment]
`es-ES_tradnl` is valid, but it seems that it's not supported in IE 11.
