### ISSUE TITLE
Language isn't always supplied as simple language string

### ISSUE THREAD

**Issue by craiga** [craiga/unixtimesta.mp#35]
Language string as reported by browser isn't always as simple as "en-US".

https://sentry.io/craig-anderson/unixtimestamp/issues/215934328/

```
RangeError: invalid language tag: en-US,en;q=0.5
  at None (/1483885225:46:17)
  at g/</j (/jquery-3.1.1.slim.min.js:2:30162)
  at g/</k< (/jquery-3.1.1.slim.min.js:2:30478)
```

**Comment by craiga** [comment]
Sentry just reported `invalid language tag: pl,en`. Looks like accept-language parsing needs more work.

**Comment by craiga** [comment]
Addressed in https://github.com/craiga/unixtimesta.mp/pull/41
