### ISSUE TITLE
RangeError: Unsupported time zone specified undefined

### ISSUE THREAD

**Issue by craiga** [craiga/unixtimesta.mp#98]
https://sentry.io/craig-anderson/unixtimestamp/issues/457281681/

```
RangeError: Unsupported time zone specified undefined
  at new DateTimeFormat (/1518193071)
  at Date.toLocaleDateString (/1518193071)
  at HTMLDocument.<anonymous> (/1518193071:47:19)
  at j (/jquery-3.1.1.slim.min.js:2:30164)
  at k (/jquery-3.1.1.slim.min.js:2:30478)
...
(1 additional frame(s) were not displayed)
```

**Comment by craiga** [comment]
Unable to reproduce this issue.
